---
- name: REMOVE APP FROM TENANT
  #  hosts: bigip     # this refers to inventory on tower
  hosts: localhost    # this refers to inventory on tower
  gather_facts: false
  connection: local


  vars:
    uri_method: "POST"
    # default 'empty' vars to be used when first creating a new tenant
    applications: []
    # temp vars for local testing only - these will come from tower
    tower_action: remove
    tower_bigip: "local-lab"
    tower_tenant: "planets"
    tower_app_name: mars
    tower_app_template: http
    tower_app_vs_ip: 1.1.3.4
    tower_app_members:
      - 1.1.3.41
      - 1.1.3.42
      - 1.1.3.43


  vars_files:
    - ../../creds/big_creds.yaml


  tasks:


  - name: FORMAT USER INPUT VARIABLES INTO NESTED LIST
    set_fact:
      format_new_app: [{	"app_name": "{{ tower_app_name }}","bigip": "{{ tower_bigip }}","template": "{{ tower_app_template }}","vs_ip": "{{ tower_app_vs_ip }}","members": "{{ tower_app_members }}"}]


  - name: IF NOT EXIST, TOUCH TENANT CONFIG FILE
    file:
      path: "../tenant-config/{{ tower_bigip }}/{{ tower_tenant }}.yaml"
      state: touch


  - name: GET APPLICATION VARS FROM TENANT CONFIG FILE
    include_vars:
      file: '../tenant-config/{{ tower_bigip }}/{{ tower_tenant }}.yaml'


  - name: DEBUG - APPLICATION VAR *** BEFORE *** 
    debug:
      msg: "write existing 'applications' {{ applications }} *** BEFORE *** "


  - name: IF APPLICATION VAR EMPTY, ADD NEW APP TO VAR
    set_fact:
      applications: "{{ format_new_app }}"
    when: applications is not defined


  - name: DEBUG - APPLICATION VAR *** AFTER *** 
    debug:
      msg: "write existing 'applications' {{ applications }} *** AFTER *** "


  - name: COUNT APPS IN ORIGIN APPLICATION VAR 
    set_fact:
      existing_apps_length: "{{ applications|length }}"


  - name: DELETE (DIFFERENCE) NEW APP TO APPLICATIONS VAR
    set_fact:
      new_applications: '{{ applications | difference(format_new_app) }}'
  

  - name: COUNT APPS IN UPDATED APPLICATION VAR 
    set_fact:
      new_apps_length: "{{ new_applications|length }}"

  - name: RENDER TEMPLATE
    set_fact:
      tenant_body: "{{ lookup('template', '../j2/multi_app_macro.j2', split_lines=False) }}"


  - name: DEBUG - TENANT BODY (AS3)
    debug:
      msg: "{{ tenant_body }}"


  - name: URI POST AS3 TO BIG-IP '{{ tower_bigip }}', TENANT '{{ tower_tenant }}'
    uri:
       #url: "https://{{ inventory_hostname }}/mgmt/shared/appsvcs/declare"
       # temporary for local testing
       url: "https://10.1.1.245/mgmt/shared/appsvcs/declare"
       #url: "https://18.197.139.41/mgmt/shared/appsvcs/declare"
       method: "{{ uri_method }}"
       #user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
       #password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
       # temporary for local testing
       user: "{{bigip_user_easy}}"
       password: "{{bigip_pass_easy}}"
       validate_certs: no
       body: "{{ tenant_body }}"
       body_format: json

# After AS3 is successfully deployed, update the source of truth

  - name: WRITE NEW SOURCE OF TRUTH TO LOCAL FILE
    copy:
      content: "{{ { tower_tenant: new_applications } | to_nice_yaml() }}"
      dest: '../tenant-config/{{ tower_bigip }}/{{ tower_tenant }}.yaml'
  
  
  - name: GIT COMMIT 
    shell: git commit -a -m 'update ../tenant-config/{{ tower_bigip }}/{{ tower_tenant }}.yaml'
    register: command_result
    failed_when: "'fail' in command_result.stdout"


  - name: DEBUG GIT OUTPUT
    debug:
      msg: "git returned = {{ command_result.stdout }}"
  

  - name: GIT PUSH
    shell: git push  
  

  

  
