---
- name: Append new app to tenant
  #  hosts: bigip     # this refers to inventory on tower
  hosts: localhost    # this refers to inventory on tower
  gather_facts: false
  connection: local
    
  vars:
    uri_method: "POST"
    # default 'empty' vars to be used when first creating a new tenant
    applications: []
    # temp vars for local testing only - these will come from tower
    tower_bigip: "local-lab"


  tasks:

    # first ensure our target directory exists
  - name: Ensure target directory exists
    file:
      dest: '../tenant-config/{{ tower_bigip }}'
      state: directory

  - set_fact:
      tenants: []
      declaration: []

  # copy each file over that matches the given pattern
  - set_fact:
      include_vars:
      #  file: '../tenant-config/{{ tower_bigip }}/{{ item | basename }}'
        dir: '../tenant-config/{{ tower_bigip }}/'
        extensions: [yaml]
      tenants: "{{ tenants }} +  [ '{{ (item | basename | splitext)[0] }}' ]"
    with_fileglob:
      - "../tenant-config/{{ tower_bigip }}/*"
  - debug:
      var: applications


  - set_fact: 
      tenant_list: "{{ tenants | to_json }}"
  - debug:
      msg: "tenants are: {{ tenant_list }} "    

  - name: render template
    set_fact:
      tenant_body: "{{ lookup('template', '../j2/multi_app_all_tenants_macro.j2', split_lines=False) }}"

  - debug:
      msg: "tenants declaration: {{ tenant_body }} "  
    